### ISSUE TITLE
No package metadata was found for gyp

### ISSUE THREAD

**Issue by mika-data** [adius/CityViz#3]
OS VERSION:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

== Installation steps: ==
```
git clone https://github.com/adius/CityViz
cd CityViz
npm install

```

== Error: ==

```
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 33, in <module>
npm ERR!     sys.exit(load_entry_point('gyp==0.1', 'console_scripts', 'gyp')())
npm ERR!   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 22, in importlib_load_entry_point
npm ERR!     for entry_point in distribution(dist_name).entry_points
npm ERR!   File "/home/user/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 558, in distribution
npm ERR!     return Distribution.from_name(distribution_name)
npm ERR!   File "/home/user/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 215, in from_name
npm ERR!     raise PackageNotFoundError(name)
npm ERR! importlib_metadata.PackageNotFoundError: No package metadata was found for gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.10.0-9-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /opt/Programming/CityViz/node_modules/node-expat
npm ERR! gyp ERR! node -v v12.22.12
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

```

node-gyp -v
v7.1.2

**Comment by ad-si** [comment]
Should be fixed by now.
